function getCountries() {
  return [
    { name: "American Samoa", code: "AS" },
    { name: "Andorra", code: "AD" },
    { name: "Argentina", code: "AR" },
    { name: "Australia", code: "AU" },
    { name: "Austria", code: "AT" },
    { name: "Bangladesh", code: "BD" },
    { name: "Belgium", code: "BE" },
    { name: "Brazil", code: "BR" },
    { name: "Bulgaria", code: "BG" },
    { name: "Canada", code: "CA" },
    { name: "Croatia", code: "HR" },
    { name: "Czech Republic", code: "CZ" },
    { name: "Denmark", code: "DK" },
    { name: "Dominican Republic", code: "DO" },
    { name: "Faroe Islands", code: "FO" },
    { name: "Finland", code: "FI" },
    { name: "France", code: "FR" },
    { name: "French Guyana", code: "GF" },
    { name: "French Reunion", code: "RE" },
    { name: "Germany", code: "DE" },
    { name: "Great Britain", code: "GB" },
    { name: "Greenland", code: "GL" },
    { name: "Guadeloupe", code: "GP" },
    { name: "Guam", code: "GU" },
    { name: "Guatemala", code: "GT" },
    { name: "Guernsey", code: "GG" },
    { name: "Guyana", code: "GY" },
    { name: "Holland", code: "NL" },
    { name: "Hungary", code: "HU" },
    { name: "Iceland", code: "IS" },
    { name: "India", code: "IN" },
    { name: "Isle of Man", code: "IM" },
    { name: "Italy", code: "IT" },
    { name: "Japan", code: "JP" },
    { name: "Jersey", code: "JE" },
    { name: "Liechtenstein", code: "LI" },
    { name: "Lithuania", code: "LT" },
    { name: "Luxembourg", code: "LU" },
    { name: "Macedonia", code: "MK" },
    { name: "Malaysia", code: "MY" },
    { name: "Marshall Islands", code: "MH" },
    { name: "Martinique", code: "MQ" },
    { name: "Mayotte", code: "YT" },
    { name: "Mexico", code: "MX" },
    { name: "Moldavia", code: "MD" },
    { name: "Monaco", code: "MC" },
    { name: "New Zealand", code: "NZ" },
    { name: "Northern Mariana Islands", code: "MP" },
    { name: "Norway", code: "NO" },
    { name: "Pakistan", code: "PK" },
    { name: "Philippines", code: "PH" },
    { name: "Poland", code: "PL" },
    { name: "Portugal", code: "PT" },
    { name: "Puerto Rico", code: "PR" },
    { name: "Russia", code: "RU" },
    { name: "Saint Pierre and Miquelon", code: "PM" },
    { name: "San Marino", code: "SM" },
    { name: "Slovak Republic", code: "SK" },
    { name: "Slovenia", code: "SI" },
    { name: "South Africa", code: "ZA" },
    { name: "Spain", code: "ES" },
    { name: "Sri Lanka", code: "LK" },
    { name: "Svalbard & Jan Mayen Islands", code: "SJ" },
    { name: "Sweden", code: "SE" },
    { name: "Switzerland", code: "CH" },
    { name: "Thailand", code: "TH" },
    { name: "Turkey", code: "TR" },
    { name: "United States", code: "US" },
    { name: "Vatican", code: "VA" },
    { name: "Virgin Islands", code: "VI" },
  ];
}

export default getCountries;
